# 带[ ]括号的，就是多选，不带的就是单选
boss:
  sayHi: "您好,这个岗位我很感兴趣,希望应聘这个岗位,请看下我的简历，期待可以与您进一步沟通,谢谢！" #必须要关闭boss的自动打招呼
  keywords: [ "财务" ] # 需要搜索的职位,会依次投递
  industry: [ "不限" ] # 公司行业，只能选三个，相关代码枚举的部分，如果需要其他的需要自己找
  cityCode: "深圳" # 只列举了部分,如果没有的需要自己找：目前支持的：全国 北京 上海 广州 深圳 成都
  experience: [ "不限" ] # 工作经验：应届毕业生,1年以下,1-3年,3-5年,5-10年,10年以上
  jobType: "不限" #求职类型：全职,兼职
  salary: "20-50K" # 薪资：3K以下,3-5K,5-10K,10-20K,20-50K,50K以上
  degree: [ "不限" ] # 学历：初中及以下,中专/中技,高中,大专,本科,硕士,博士
  scale: [ "不限" ] # 公司规模：不限,0-20人,20-99人,100-499人,500-999人,1000-9999人,10000人以上
  stage: [ "不限" ] # 未融资,天使轮,A轮,B轮,C轮,D轮及以上,已上市,不需要融资

job51:
  jobArea: [ "深圳" ]  #工作地区：目前只有【北京 成都 上海 广州 深圳】
  keywords: [ "财务" ] #关键词：依次投递
  salary: [ "1.5-2万,2-3万,3-4万,4-5万,5万以上" ] #薪资范围：只能选5个【2千以下,2-3千,3-4.5千,4.5-6千,6-8千,0.8-1万,1-1.5万,1.5-2万,2-3万,3-4万,4-5万,5万以上】

lagou:
  keyword: "AI工程师" #搜索关键词
  city: "上海" #拉勾城市名没有限制,直接填写即可
  yx: "不限" #薪资（单选）【2k以下,2k-5k,5k-10k,10k-15k,15k-25k,25k-50k,50k以上】
  gm: [ "不限" ] #公司规模（多选）【少于15人,15-50人,50-150人,150-500人,500-2000人,2000人以上】

liepin:
  cityCode: "深圳" # 目前支持的：全国 北京 上海 广州 深圳 成都
  keywords: [ "财务"]
  salary: "15$50" # 填 15$30 代表 15k-30k

zhilian:
  cityCode: "上海"
  salaryScope: "25001,35000" #薪资区间
  keywords: [ "AI工程师", "AIGC", "Java", "Python", "Golang" ]